name: watertracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  animations: ^2.0.11
  cupertino_icons: ^1.0.8  
  flutter_bloc: ^9.0.0
  rxdart: ^0.28.0
  get_it: ^8.0.3
  shared_preferences: ^2.2.2
  dynamic_color: ^1.7.0
  go_router: ^14.8.1
  very_good_analysis: ^7.0.0
  flutter_svg: ^2.0.10+1
  fl_chart: ^0.70.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/avatars/
    - assets/navbaricons/
  fonts:
    - family: AppSymbols
      fonts:
        - asset: fonts/AppSymbols.ttf
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Regular.ttf
        - asset: fonts/Comfortaa-Light.ttf
          weight: 300
        - asset: fonts/Comfortaa-Medium.ttf
          weight: 500
        - asset: fonts/Comfortaa-SemiBold.ttf
          weight: 600
        - asset: fonts/Comfortaa-Bold.ttf
          weight: 700