name: watertracker
description: "A minimalist hydration tracker built with Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  fl_chart: ^0.66.2
  flutter_svg: ^2.0.17
  lottie: ^3.3.1
  vibration: ^3.1.3
  ruler_scale_picker: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/nunito/Nunito-ExtraBold.ttf
          weight: 800

  assets:
    - assets/images/avatars/
    - assets/images/icons/navbar/
    - assets/images/icons/onboarding_elements/
    - assets/images/icons/onboarding_elements/select_your_goal_icons/
    - assets/animations/lottie/