name: watertracker
description: "A minimalist hydration tracker built with Flutter."
publish_to: 'none'

version: 0.1.4

environment:
  sdk: ^3.7.0
  flutter: ">=3.32.0"

dependencies:
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  device_info_plus: ^10.1.2
  encrypted_shared_preferences: ^3.0.1
  equatable: ^2.0.5
  fl_chart: ^0.66.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.17
  health: ^13.1.1
  http: ^1.1.0
  image_picker: ^1.0.4
  intl: any
  lottie: ^3.3.1
  path_provider: ^2.1.4
  pdf: ^3.11.1
  permission_handler: ^11.4.0
  provider: ^6.1.2
  ruler_scale_picker: ^0.1.0
  shared_preferences: ^2.5.2
  table_calendar: ^3.1.2
  timezone: ^0.9.4
  url_launcher: ^6.3.1
  vibration: ^3.1.3

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  very_good_analysis: ^5.1.0

  test: any
flutter:
  uses-material-design: true

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/nunito/Nunito-ExtraBold.ttf
          weight: 800

  assets:
    - assets/images/avatars/
    - assets/images/icons/navbar/
    - assets/images/icons/onboarding_elements/
    - assets/images/icons/onboarding_elements/select_your_goal_icons/
    - assets/animations/lottie/