// Mocks generated by Mockito 5.4.6 from annotations
// in watertracker/test/core/services/offline_storage_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:watertracker/core/services/connectivity_service.dart' as _i4;
import 'package:watertracker/core/services/storage_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFuture_0<T1> extends _i1.SmartFake implements _i2.Future<T1> {
  _FakeFuture_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i3.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<bool> saveString(
    String? key,
    String? value, {
    bool? encrypted = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #saveString,
              [key, value],
              {#encrypted: encrypted},
            ),
            returnValue: _i2.Future<bool>.value(false),
          )
          as _i2.Future<bool>);

  @override
  _i2.Future<String?> getString(String? key, {bool? encrypted = true}) =>
      (super.noSuchMethod(
            Invocation.method(#getString, [key], {#encrypted: encrypted}),
            returnValue: _i2.Future<String?>.value(),
          )
          as _i2.Future<String?>);

  @override
  _i2.Future<bool> saveInt(
    String? key,
    int? value, {
    bool? encrypted = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveInt, [key, value], {#encrypted: encrypted}),
            returnValue: _i2.Future<bool>.value(false),
          )
          as _i2.Future<bool>);

  @override
  _i2.Future<int?> getInt(String? key, {bool? encrypted = false}) =>
      (super.noSuchMethod(
            Invocation.method(#getInt, [key], {#encrypted: encrypted}),
            returnValue: _i2.Future<int?>.value(),
          )
          as _i2.Future<int?>);

  @override
  _i2.Future<bool> saveBool(
    String? key, {
    required bool? value,
    bool? encrypted = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #saveBool,
              [key],
              {#value: value, #encrypted: encrypted},
            ),
            returnValue: _i2.Future<bool>.value(false),
          )
          as _i2.Future<bool>);

  @override
  _i2.Future<bool?> getBool(String? key, {bool? encrypted = false}) =>
      (super.noSuchMethod(
            Invocation.method(#getBool, [key], {#encrypted: encrypted}),
            returnValue: _i2.Future<bool?>.value(),
          )
          as _i2.Future<bool?>);

  @override
  _i2.Future<bool> saveDouble(
    String? key,
    double? value, {
    bool? encrypted = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #saveDouble,
              [key, value],
              {#encrypted: encrypted},
            ),
            returnValue: _i2.Future<bool>.value(false),
          )
          as _i2.Future<bool>);

  @override
  _i2.Future<double?> getDouble(String? key, {bool? encrypted = false}) =>
      (super.noSuchMethod(
            Invocation.method(#getDouble, [key], {#encrypted: encrypted}),
            returnValue: _i2.Future<double?>.value(),
          )
          as _i2.Future<double?>);

  @override
  _i2.Future<bool> saveStringList(
    String? key,
    List<String>? value, {
    bool? encrypted = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #saveStringList,
              [key, value],
              {#encrypted: encrypted},
            ),
            returnValue: _i2.Future<bool>.value(false),
          )
          as _i2.Future<bool>);

  @override
  _i2.Future<List<String>?> getStringList(
    String? key, {
    bool? encrypted = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getStringList, [key], {#encrypted: encrypted}),
            returnValue: _i2.Future<List<String>?>.value(),
          )
          as _i2.Future<List<String>?>);

  @override
  _i2.Future<bool> remove(String? key, {bool? encrypted = false}) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key], {#encrypted: encrypted}),
            returnValue: _i2.Future<bool>.value(false),
          )
          as _i2.Future<bool>);

  @override
  _i2.Future<bool> containsKey(String? key, {bool? encrypted = false}) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key], {#encrypted: encrypted}),
            returnValue: _i2.Future<bool>.value(false),
          )
          as _i2.Future<bool>);

  @override
  _i2.Future<bool> saveJson(
    String? key,
    Map<String, dynamic>? data, {
    bool? encrypted = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveJson, [key, data], {#encrypted: encrypted}),
            returnValue: _i2.Future<bool>.value(false),
          )
          as _i2.Future<bool>);

  @override
  _i2.Future<Map<String, dynamic>?> getJson(
    String? key, {
    bool? encrypted = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getJson, [key], {#encrypted: encrypted}),
            returnValue: _i2.Future<Map<String, dynamic>?>.value(),
          )
          as _i2.Future<Map<String, dynamic>?>);

  @override
  _i2.Future<bool> createBackup({String? customPath}) =>
      (super.noSuchMethod(
            Invocation.method(#createBackup, [], {#customPath: customPath}),
            returnValue: _i2.Future<bool>.value(false),
          )
          as _i2.Future<bool>);

  @override
  _i2.Future<bool> restoreFromBackup(String? backupPath) =>
      (super.noSuchMethod(
            Invocation.method(#restoreFromBackup, [backupPath]),
            returnValue: _i2.Future<bool>.value(false),
          )
          as _i2.Future<bool>);

  @override
  _i2.Future<List<String>> getAvailableBackups() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableBackups, []),
            returnValue: _i2.Future<List<String>>.value(<String>[]),
          )
          as _i2.Future<List<String>>);

  @override
  _i2.Future<void> markForSync(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#markForSync, [key]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<List<String>> getSyncQueue() =>
      (super.noSuchMethod(
            Invocation.method(#getSyncQueue, []),
            returnValue: _i2.Future<List<String>>.value(<String>[]),
          )
          as _i2.Future<List<String>>);

  @override
  _i2.Future<void> removeFromSyncQueue(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromSyncQueue, [key]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> clearSyncQueue() =>
      (super.noSuchMethod(
            Invocation.method(#clearSyncQueue, []),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<bool> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i2.Future<bool>.value(false),
          )
          as _i2.Future<bool>);

  @override
  _i2.Future<Map<String, dynamic>> getStorageStats() =>
      (super.noSuchMethod(
            Invocation.method(#getStorageStats, []),
            returnValue: _i2.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i2.Future<Map<String, dynamic>>);

  @override
  _i2.Future<String?> getStringCached(String? key, {bool? encrypted = true}) =>
      (super.noSuchMethod(
            Invocation.method(#getStringCached, [key], {#encrypted: encrypted}),
            returnValue: _i2.Future<String?>.value(),
          )
          as _i2.Future<String?>);

  @override
  void clearMemoryCache() => super.noSuchMethod(
    Invocation.method(#clearMemoryCache, []),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> getCacheStats() =>
      (super.noSuchMethod(
            Invocation.method(#getCacheStats, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i2.Future<bool> isHealthy() =>
      (super.noSuchMethod(
            Invocation.method(#isHealthy, []),
            returnValue: _i2.Future<bool>.value(false),
          )
          as _i2.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i4.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Stream<bool> get connectivityStream =>
      (super.noSuchMethod(
            Invocation.getter(#connectivityStream),
            returnValue: _i2.Stream<bool>.empty(),
          )
          as _i2.Stream<bool>);

  @override
  bool get isOnline =>
      (super.noSuchMethod(Invocation.getter(#isOnline), returnValue: false)
          as bool);

  @override
  _i2.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<bool> checkConnectivity() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnectivity, []),
            returnValue: _i2.Future<bool>.value(false),
          )
          as _i2.Future<bool>);

  @override
  _i2.Future<T> executeWithConnectivity<T>(
    _i2.Future<T> Function()? operation, {
    T? offlineFallback,
    bool? requiresConnection = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #executeWithConnectivity,
              [operation],
              {
                #offlineFallback: offlineFallback,
                #requiresConnection: requiresConnection,
              },
            ),
            returnValue:
                _i5.ifNotNull(
                  _i5.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #executeWithConnectivity,
                      [operation],
                      {
                        #offlineFallback: offlineFallback,
                        #requiresConnection: requiresConnection,
                      },
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #executeWithConnectivity,
                    [operation],
                    {
                      #offlineFallback: offlineFallback,
                      #requiresConnection: requiresConnection,
                    },
                  ),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<void> waitForConnectivity({Duration? timeout}) =>
      (super.noSuchMethod(
            Invocation.method(#waitForConnectivity, [], {#timeout: timeout}),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
